steps:

- name: golang
  id: 'buildGame'
  env: ['GO111MODULE=on','GOOS=js','GOARCH=wasm']
  dir: 'game'
  args: ['go', 'build','-o', '../react/static/main.wasm', 'main.go']

- name: 'gcr.io/cloud-builders/yarn'
  waitFor: ['-']
  id: 'installYarnDependencies'
  dir: 'react'
  args: ['install']

- name: 'gcr.io/cloud-builders/yarn'
  waitFor: ['buildGame', 'installYarnDependencies']
  id: 'buildApp'
  dir: 'react'
  args: ['build']

- name: 'gcr.io/cloud-builders/gcloud'
  waitFor: ['buildApp']
  id: 'deployApp'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      set -e
      if [[ "$BRANCH_NAME" == "master" ]]; then 
        gcloud app deploy server/app.yaml
      else 
        gcloud app deploy server/app.yaml --no-promote
      fi