service: launch
runtime: go111

handlers:
  # If the path is empty, show static index.html file
- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /static/main\.wasm
  static_files: dist/static/main.wasm
  upload: dist/static/main\.wasm
  mime_type: application/wasm

- url: /static
  static_dir: dist/static

- url: /.*
  static_dir: dist

