service: launch
runtime: go112

handlers:
  # If the path is empty, show static index.html file
- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /.*
  static_dir: dist

